services:
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-backend-db
          property: connectionString

databases:
  - name: portfolio-backend-db
    plan: free